server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
  adminConnectors:
    - type: https
      port: 8444
      keyStorePath: example.keystore
      keyStorePassword: example

logging:
  level: INFO
  loggers:
    org.kainos.ea: DEBUG

swagger:
  resourcePackage: org.kainos.ea